"""single_initial_merged_migration

Revision ID: 08560d317e5a
Revises: 
Create Date: 2025-10-18 15:05:02.453509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08560d317e5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if bill table exists before creating it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()

    op.create_table('contractor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('contact_person', sa.String(length=128), nullable=True),
    sa.Column('contact_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('company_name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=False)
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_table('photo_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('max_photos', sa.Integer(), nullable=True),
    sa.Column('max_size_mb', sa.Float(), nullable=True),
    sa.Column('allowed_formats', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage')
    )
    op.create_table('postal_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postal_codes_id'), 'postal_codes', ['id'], unique=False)
    op.create_index(op.f('ix_postal_codes_postal_code'), 'postal_codes', ['postal_code'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('create', sa.DateTime(), nullable=True),
    sa.Column('update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contractor_service_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contractor_id', 'service_id', name='unique_contractor_service')
    )
    op.create_table('customer_service_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_id', 'service_id', 'vehicle_type_id', name='uq_csp_cust_service_vehicle')
    )
    op.create_index(op.f('ix_customer_service_pricing_cust_id'), 'customer_service_pricing', ['cust_id'], unique=False)
    op.create_index(op.f('ix_customer_service_pricing_service_id'), 'customer_service_pricing', ['service_id'], unique=False)
    op.create_index(op.f('ix_customer_service_pricing_vehicle_type_id'), 'customer_service_pricing', ['vehicle_type_id'], unique=False)
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('remaining_amount_invoice', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_customer_id'), 'invoice', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoice_status'), 'invoice', ['status'], unique=False)
    op.create_table('service_vehicle_type_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'customer_id', name='_subcustomer_uc')
    )
    op.create_index(op.f('ix_sub_customer_customer_id'), 'sub_customer', ['customer_id'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sub_customer_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=64), nullable=False),
    sa.Column('pickup_location', sa.String(length=256), nullable=False),
    sa.Column('dropoff_location', sa.String(length=256), nullable=False),
    sa.Column('pickup_date', sa.String(length=32), nullable=False),
    sa.Column('pickup_time', sa.String(length=32), nullable=True),
    sa.Column('passenger_name', sa.String(length=128), nullable=True),
    sa.Column('passenger_email', sa.String(length=128), nullable=True),
    sa.Column('passenger_mobile', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('extra_services', sa.Text(), nullable=True),
    sa.Column('additional_discount', sa.Float(), nullable=True),
    sa.Column('extra_charges', sa.Float(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('job_cost', sa.Float(), nullable=True),
    sa.Column('cash_to_collect', sa.Float(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('driver_commission', sa.Float(), nullable=True),
    sa.Column('penalty', sa.Float(), nullable=True),
    sa.Column('dropoff_loc1', sa.Text(), nullable=True),
    sa.Column('dropoff_loc2', sa.Text(), nullable=True),
    sa.Column('dropoff_loc3', sa.Text(), nullable=True),
    sa.Column('dropoff_loc4', sa.Text(), nullable=True),
    sa.Column('dropoff_loc5', sa.Text(), nullable=True),
    sa.Column('dropoff_loc1_price', sa.Float(), nullable=True),
    sa.Column('dropoff_loc2_price', sa.Float(), nullable=True),
    sa.Column('dropoff_loc3_price', sa.Float(), nullable=True),
    sa.Column('dropoff_loc4_price', sa.Float(), nullable=True),
    sa.Column('dropoff_loc5_price', sa.Float(), nullable=True),
    sa.Column('pickup_loc1', sa.Text(), nullable=True),
    sa.Column('pickup_loc2', sa.Text(), nullable=True),
    sa.Column('pickup_loc3', sa.Text(), nullable=True),
    sa.Column('pickup_loc4', sa.Text(), nullable=True),
    sa.Column('pickup_loc5', sa.Text(), nullable=True),
    sa.Column('pickup_loc1_price', sa.Float(), nullable=True),
    sa.Column('pickup_loc2_price', sa.Float(), nullable=True),
    sa.Column('pickup_loc3_price', sa.Float(), nullable=True),
    sa.Column('pickup_loc4_price', sa.Float(), nullable=True),
    sa.Column('pickup_loc5_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('customer_remark', sa.Text(), nullable=True),
    sa.Column('midnight_surcharge', sa.Float(), nullable=True),
    sa.CheckConstraint("status IN ('new', 'pending', 'confirmed', 'otw', 'ots', 'pob', 'jc', 'sd', 'canceled')", name='check_job_status'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sub_customer_id'], ['sub_customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_type.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_contractor_id'), 'job', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_job_customer_id'), 'job', ['customer_id'], unique=False)
    op.create_index(op.f('ix_job_driver_id'), 'job', ['driver_id'], unique=False)
    op.create_index(op.f('ix_job_invoice_id'), 'job', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_job_pickup_date'), 'job', ['pickup_date'], unique=False)
    op.create_index(op.f('ix_job_service_id'), 'job', ['service_id'], unique=False)
    op.create_index(op.f('ix_job_service_type'), 'job', ['service_type'], unique=False)
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.create_index(op.f('ix_job_sub_customer_id'), 'job', ['sub_customer_id'], unique=False)
    op.create_index(op.f('ix_job_vehicle_id'), 'job', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_job_vehicle_type_id'), 'job', ['vehicle_type_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('receipt_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_invoice_id'), 'payment', ['invoice_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('fs_uniquifier', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=100), nullable=True),
    sa.Column('current_login_ip', sa.String(length=100), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('android_device_token', sa.String(length=1024), nullable=True),
    sa.Column('ios_device_token', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier')
    )
    op.create_table('driver_remark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_photo_driver_id'), 'job_photo', ['driver_id'], unique=False)
    op.create_index(op.f('ix_job_photo_file_hash'), 'job_photo', ['file_hash'], unique=False)
    op.create_index(op.f('ix_job_photo_job_id'), 'job_photo', ['job_id'], unique=False)
    op.create_table('password_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('salt', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_token_token_hash'), 'password_reset_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_token_user_id'), 'password_reset_token', ['user_id'], unique=False)
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_settings_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_table('roles_users')
    op.drop_index(op.f('ix_password_reset_token_user_id'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_token_hash'), table_name='password_reset_token')
    op.drop_table('password_reset_token')
    op.drop_index(op.f('ix_job_photo_job_id'), table_name='job_photo')
    op.drop_index(op.f('ix_job_photo_file_hash'), table_name='job_photo')
    op.drop_index(op.f('ix_job_photo_driver_id'), table_name='job_photo')
    op.drop_table('job_photo')
    op.drop_table('job_audit')
    op.drop_table('driver_remark')
    op.drop_table('user')
    op.drop_index(op.f('ix_payment_invoice_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_job_vehicle_type_id'), table_name='job')
    op.drop_index(op.f('ix_job_vehicle_id'), table_name='job')
    op.drop_index(op.f('ix_job_sub_customer_id'), table_name='job')
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_index(op.f('ix_job_service_type'), table_name='job')
    op.drop_index(op.f('ix_job_service_id'), table_name='job')
    op.drop_index(op.f('ix_job_pickup_date'), table_name='job')
    op.drop_index(op.f('ix_job_invoice_id'), table_name='job')
    op.drop_index(op.f('ix_job_driver_id'), table_name='job')
    op.drop_index(op.f('ix_job_customer_id'), table_name='job')
    op.drop_index(op.f('ix_job_contractor_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_sub_customer_customer_id'), table_name='sub_customer')
    op.drop_table('sub_customer')
    op.drop_table('service_vehicle_type_price')
    op.drop_index(op.f('ix_invoice_status'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_customer_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_table('driver')
    op.drop_index(op.f('ix_customer_service_pricing_vehicle_type_id'), table_name='customer_service_pricing')
    op.drop_index(op.f('ix_customer_service_pricing_service_id'), table_name='customer_service_pricing')
    op.drop_index(op.f('ix_customer_service_pricing_cust_id'), table_name='customer_service_pricing')
    op.drop_table('customer_service_pricing')
    op.drop_table('contractor_service_pricing')
    op.drop_table('vehicle_type')
    op.drop_table('vehicle')
    op.drop_table('service')
    op.drop_table('role')
    op.drop_index(op.f('ix_postal_codes_postal_code'), table_name='postal_codes')
    op.drop_index(op.f('ix_postal_codes_id'), table_name='postal_codes')
    op.drop_table('postal_codes')
    op.drop_table('photo_config')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('contractor')
    # ### end Alembic commands ###
