"""db migration released on 20Oct2025

Revision ID: 3da07bea5123
Revises: 08560d317e5a
Create Date: 2025-10-22 01:13:31.839122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da07bea5123'
down_revision: Union[str, Sequence[str], None] = '08560d317e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_contractor_id'), 'bill', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_bill_driver_id'), 'bill', ['driver_id'], unique=False)
    op.create_index(op.f('ix_bill_status'), 'bill', ['status'], unique=False)
    
    # Use batch mode for SQLite to modify job table
    with op.batch_alter_table('job', schema=None, copy_from=None) as batch_op:
        batch_op.drop_index('ix_job_sub_customer_id')
        batch_op.drop_column('sub_customer_id')
        batch_op.add_column(sa.Column('sub_customer_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('booking_ref', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_booking_ref'), ['booking_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_bill_id'), ['bill_id'], unique=False)
        batch_op.create_foreign_key('fk_job_bill_id_bill', 'bill', ['bill_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite to modify job table
    with op.batch_alter_table('job', schema=None, copy_from=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_bill_id'))
        batch_op.drop_index(batch_op.f('ix_job_booking_ref'))
        batch_op.drop_column('bill_id')
        batch_op.drop_column('booking_ref')
        batch_op.drop_column('sub_customer_name')
        batch_op.add_column(sa.Column('sub_customer_id', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_job_sub_customer_id', ['sub_customer_id'], unique=False)
        batch_op.create_foreign_key(None, 'sub_customer', ['sub_customer_id'], ['id'], ondelete='CASCADE')
    
    op.drop_index(op.f('ix_bill_status'), table_name='bill')
    op.drop_index(op.f('ix_bill_driver_id'), table_name='bill')
    op.drop_index(op.f('ix_bill_contractor_id'), table_name='bill')
    op.drop_table('bill')
    
    # ### end Alembic commands ###
